// Code generated by protoc-gen-go. DO NOT EDIT.
// source: price/price/price.proto

package price

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPricesRequest struct {
	Symbols              []string `protobuf:"bytes,1,rep,name=Symbols,proto3" json:"Symbols,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPricesRequest) Reset()         { *m = GetPricesRequest{} }
func (m *GetPricesRequest) String() string { return proto.CompactTextString(m) }
func (*GetPricesRequest) ProtoMessage()    {}
func (*GetPricesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d539350e99067cbd, []int{0}
}

func (m *GetPricesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPricesRequest.Unmarshal(m, b)
}
func (m *GetPricesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPricesRequest.Marshal(b, m, deterministic)
}
func (m *GetPricesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPricesRequest.Merge(m, src)
}
func (m *GetPricesRequest) XXX_Size() int {
	return xxx_messageInfo_GetPricesRequest.Size(m)
}
func (m *GetPricesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPricesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPricesRequest proto.InternalMessageInfo

func (m *GetPricesRequest) GetSymbols() []string {
	if m != nil {
		return m.Symbols
	}
	return nil
}

type GetPricesResponse struct {
	Prices               map[string]float64 `protobuf:"bytes,1,rep,name=Prices,proto3" json:"Prices,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetPricesResponse) Reset()         { *m = GetPricesResponse{} }
func (m *GetPricesResponse) String() string { return proto.CompactTextString(m) }
func (*GetPricesResponse) ProtoMessage()    {}
func (*GetPricesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d539350e99067cbd, []int{1}
}

func (m *GetPricesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPricesResponse.Unmarshal(m, b)
}
func (m *GetPricesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPricesResponse.Marshal(b, m, deterministic)
}
func (m *GetPricesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPricesResponse.Merge(m, src)
}
func (m *GetPricesResponse) XXX_Size() int {
	return xxx_messageInfo_GetPricesResponse.Size(m)
}
func (m *GetPricesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPricesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPricesResponse proto.InternalMessageInfo

func (m *GetPricesResponse) GetPrices() map[string]float64 {
	if m != nil {
		return m.Prices
	}
	return nil
}

func init() {
	proto.RegisterType((*GetPricesRequest)(nil), "price.GetPricesRequest")
	proto.RegisterType((*GetPricesResponse)(nil), "price.GetPricesResponse")
	proto.RegisterMapType((map[string]float64)(nil), "price.GetPricesResponse.PricesEntry")
}

func init() { proto.RegisterFile("price/price/price.proto", fileDescriptor_d539350e99067cbd) }

var fileDescriptor_d539350e99067cbd = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x4c,
	0x4e, 0xd5, 0x47, 0x22, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x58, 0xc1, 0x1c, 0x25, 0x1d,
	0x2e, 0x01, 0xf7, 0xd4, 0x92, 0x00, 0x10, 0xbb, 0x38, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44,
	0x48, 0x82, 0x8b, 0x3d, 0xb8, 0x32, 0x37, 0x29, 0x3f, 0xa7, 0x58, 0x82, 0x51, 0x81, 0x59, 0x83,
	0x33, 0x08, 0xc6, 0x55, 0xea, 0x61, 0xe4, 0x12, 0x44, 0x52, 0x5e, 0x5c, 0x90, 0x9f, 0x57, 0x9c,
	0x2a, 0x64, 0xc3, 0xc5, 0x06, 0x11, 0x01, 0x2b, 0xe7, 0x36, 0x52, 0xd1, 0x83, 0x58, 0x84, 0xa1,
	0x52, 0x0f, 0xc2, 0x75, 0xcd, 0x2b, 0x29, 0xaa, 0x0c, 0x82, 0xea, 0x91, 0xb2, 0xe4, 0xe2, 0x46,
	0x12, 0x16, 0x12, 0xe0, 0x62, 0xce, 0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02,
	0x31, 0x85, 0x44, 0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x18,
	0x83, 0x20, 0x1c, 0x2b, 0x26, 0x0b, 0x46, 0xa3, 0x00, 0x2e, 0x1e, 0xb0, 0xd6, 0xe0, 0xd4, 0xa2,
	0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x07, 0x2e, 0x4e, 0xb8, 0x9d, 0x42, 0xe2, 0x98, 0xae, 0x00, 0x7b,
	0x4f, 0x4a, 0x02, 0x97, 0xf3, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x81, 0x63, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x38, 0x13, 0xad, 0x33, 0x37, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PriceServiceClient is the client API for PriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PriceServiceClient interface {
	GetPrices(ctx context.Context, in *GetPricesRequest, opts ...grpc.CallOption) (*GetPricesResponse, error)
}

type priceServiceClient struct {
	cc *grpc.ClientConn
}

func NewPriceServiceClient(cc *grpc.ClientConn) PriceServiceClient {
	return &priceServiceClient{cc}
}

func (c *priceServiceClient) GetPrices(ctx context.Context, in *GetPricesRequest, opts ...grpc.CallOption) (*GetPricesResponse, error) {
	out := new(GetPricesResponse)
	err := c.cc.Invoke(ctx, "/price.PriceService/GetPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PriceServiceServer is the server API for PriceService service.
type PriceServiceServer interface {
	GetPrices(context.Context, *GetPricesRequest) (*GetPricesResponse, error)
}

func RegisterPriceServiceServer(s *grpc.Server, srv PriceServiceServer) {
	s.RegisterService(&_PriceService_serviceDesc, srv)
}

func _PriceService_GetPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServiceServer).GetPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/price.PriceService/GetPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServiceServer).GetPrices(ctx, req.(*GetPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PriceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "price.PriceService",
	HandlerType: (*PriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrices",
			Handler:    _PriceService_GetPrices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "price/price/price.proto",
}
