// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pricelist/pricelist/pricelist.proto

package pricelist

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPricelistRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPricelistRequest) Reset()         { *m = GetPricelistRequest{} }
func (m *GetPricelistRequest) String() string { return proto.CompactTextString(m) }
func (*GetPricelistRequest) ProtoMessage()    {}
func (*GetPricelistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cb252e5acfffd22, []int{0}
}

func (m *GetPricelistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPricelistRequest.Unmarshal(m, b)
}
func (m *GetPricelistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPricelistRequest.Marshal(b, m, deterministic)
}
func (m *GetPricelistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPricelistRequest.Merge(m, src)
}
func (m *GetPricelistRequest) XXX_Size() int {
	return xxx_messageInfo_GetPricelistRequest.Size(m)
}
func (m *GetPricelistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPricelistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPricelistRequest proto.InternalMessageInfo

func (m *GetPricelistRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetPricelistResponse struct {
	Positions            []*Position `protobuf:"bytes,1,rep,name=Positions,proto3" json:"Positions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetPricelistResponse) Reset()         { *m = GetPricelistResponse{} }
func (m *GetPricelistResponse) String() string { return proto.CompactTextString(m) }
func (*GetPricelistResponse) ProtoMessage()    {}
func (*GetPricelistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cb252e5acfffd22, []int{1}
}

func (m *GetPricelistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPricelistResponse.Unmarshal(m, b)
}
func (m *GetPricelistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPricelistResponse.Marshal(b, m, deterministic)
}
func (m *GetPricelistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPricelistResponse.Merge(m, src)
}
func (m *GetPricelistResponse) XXX_Size() int {
	return xxx_messageInfo_GetPricelistResponse.Size(m)
}
func (m *GetPricelistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPricelistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPricelistResponse proto.InternalMessageInfo

func (m *GetPricelistResponse) GetPositions() []*Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

type Position struct {
	Rank                 int32    `protobuf:"varint,1,opt,name=Rank,proto3" json:"Rank,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	PriceUSD             float64  `protobuf:"fixed64,3,opt,name=PriceUSD,proto3" json:"PriceUSD,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cb252e5acfffd22, []int{2}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *Position) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Position) GetPriceUSD() float64 {
	if m != nil {
		return m.PriceUSD
	}
	return 0
}

func init() {
	proto.RegisterType((*GetPricelistRequest)(nil), "pricelist.GetPricelistRequest")
	proto.RegisterType((*GetPricelistResponse)(nil), "pricelist.GetPricelistResponse")
	proto.RegisterType((*Position)(nil), "pricelist.Position")
}

func init() {
	proto.RegisterFile("pricelist/pricelist/pricelist.proto", fileDescriptor_0cb252e5acfffd22)
}

var fileDescriptor_0cb252e5acfffd22 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x4a, 0xc5, 0x30,
	0x14, 0x84, 0x8d, 0xd7, 0x7b, 0xb9, 0x3d, 0xba, 0x90, 0xd3, 0x22, 0xa1, 0x0b, 0x0d, 0x71, 0x13,
	0x10, 0x2a, 0xd6, 0x57, 0x10, 0xc4, 0x5d, 0x4d, 0xf1, 0x01, 0x6c, 0x39, 0x8b, 0x60, 0xdb, 0xd4,
	0x26, 0x0a, 0xbe, 0xbd, 0xd0, 0x7f, 0xa1, 0xee, 0xce, 0x97, 0x19, 0x98, 0x99, 0xc0, 0x6d, 0xdb,
	0x99, 0x92, 0x2a, 0xe3, 0xfc, 0xfd, 0xc6, 0x95, 0xb4, 0x9d, 0xf5, 0x16, 0x83, 0xf9, 0x41, 0xde,
	0x41, 0xf8, 0x4c, 0x3e, 0x9b, 0x58, 0xd3, 0xe7, 0x17, 0x39, 0x8f, 0x11, 0xec, 0x2b, 0x53, 0x1b,
	0xcf, 0x99, 0x60, 0x6a, 0xaf, 0x07, 0x90, 0x2f, 0x10, 0xfd, 0x35, 0xbb, 0xd6, 0x36, 0x8e, 0xf0,
	0x01, 0x82, 0xcc, 0x3a, 0xe3, 0x8d, 0x6d, 0x1c, 0x67, 0x62, 0xa7, 0xce, 0xd3, 0x30, 0x59, 0x42,
	0x27, 0x4d, 0x2f, 0x2e, 0xa9, 0xe1, 0x38, 0x01, 0x22, 0x9c, 0xe9, 0xf7, 0xe6, 0x63, 0xcc, 0xea,
	0x6f, 0xbc, 0x82, 0x43, 0xfe, 0x53, 0x17, 0xb6, 0xe2, 0xa7, 0x82, 0xa9, 0x40, 0x8f, 0x84, 0x31,
	0x1c, 0xfb, 0xfc, 0xb7, 0xfc, 0x89, 0xef, 0x04, 0x53, 0x4c, 0xcf, 0x9c, 0x12, 0x5c, 0xce, 0xdd,
	0x72, 0xea, 0xbe, 0x4d, 0x49, 0xf8, 0x0a, 0x17, 0xeb, 0xca, 0x78, 0xbd, 0xea, 0xb5, 0x31, 0x3c,
	0xbe, 0xf9, 0x57, 0x1f, 0xb6, 0xca, 0x93, 0xe2, 0xd0, 0x7f, 0xe2, 0xe3, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x7a, 0xbb, 0x3c, 0x75, 0x6b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PricelistServiceClient is the client API for PricelistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PricelistServiceClient interface {
	GetPricelist(ctx context.Context, in *GetPricelistRequest, opts ...grpc.CallOption) (*GetPricelistResponse, error)
}

type pricelistServiceClient struct {
	cc *grpc.ClientConn
}

func NewPricelistServiceClient(cc *grpc.ClientConn) PricelistServiceClient {
	return &pricelistServiceClient{cc}
}

func (c *pricelistServiceClient) GetPricelist(ctx context.Context, in *GetPricelistRequest, opts ...grpc.CallOption) (*GetPricelistResponse, error) {
	out := new(GetPricelistResponse)
	err := c.cc.Invoke(ctx, "/pricelist.PricelistService/GetPricelist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PricelistServiceServer is the server API for PricelistService service.
type PricelistServiceServer interface {
	GetPricelist(context.Context, *GetPricelistRequest) (*GetPricelistResponse, error)
}

func RegisterPricelistServiceServer(s *grpc.Server, srv PricelistServiceServer) {
	s.RegisterService(&_PricelistService_serviceDesc, srv)
}

func _PricelistService_GetPricelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPricelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricelistServiceServer).GetPricelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pricelist.PricelistService/GetPricelist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricelistServiceServer).GetPricelist(ctx, req.(*GetPricelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PricelistService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pricelist.PricelistService",
	HandlerType: (*PricelistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPricelist",
			Handler:    _PricelistService_GetPricelist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pricelist/pricelist/pricelist.proto",
}
